###########
# site.title, site.url, site.author.name

title: 'Team Tech Blog'
author:
  name: 'Mayflower'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#  path: /jekyll-minimal-theme
base: ""
url:  'https://blog.mayflower.tech'

########
# more settings

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

